kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-efs
  annotations:
    volume.beta.kubernetes.io/storage-class: "efs-sc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi