apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: airflow
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - name: efs-nginx
            mountPath: "/usr/share/nginx/html"
      volumes:
        - name: efs-nginx
          persistentVolumeClaim:
            claimName: airflow-efs-pvc