kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: eks-efs
  namespace: eks-airflow
provisioner: efs-provisioner

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-airflow-claim
  namespace: eks-airflow
  annotations:
    volume.beta.kubernetes.io/storage-class: "eks-efs"

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
