kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs
  namespace: eks-airflow
  annotations:
    volume.beta.kubernetes.io/storage-class: "eks-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi