###################################
# Airflow - Common Configs
###################################
airflow:
  legacyCommands: false

  image:
    repository: apache/airflow
    tag: 2.1.2-python3.9
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 50000
    gid: 50000

  executor: CeleryExecutor
  fernetKey: "Ilwvenf8Bcni1qpZg3v7StIOCdYnc6Zz2TPAtOtDmss="
  config:
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
    AIRFLOW__CORE__LOAD_EXAMPLES: "True"
    GUNICORN_CMD_ARGS: "--log-level WARNING"
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "60"

  users:
    - username: admin
      password: admin
      role: Admin
      email: sys@kakao.com
      firstName: Yunsung
      lastName: Song

  usersTemplates: {}
  usersUpdate: true
  connections:
  connectionsTemplates: {}
  connectionsUpdate: true
  variables: []
  variablesTemplates: {}
  variablesUpdate: true
  pools: []
  poolsUpdate: true
  extraPipPackages:
    - "pandahouse==0.2.7"
    - "clickhouse-driver==0.2.1"

  extraEnv: []
  extraContainers: []

  extraVolumeMounts: []
  extraVolumes: []

  kubernetesPodTemplate:
    securityContext:
      fsGroup: 65534
    stringOverride: ""
    nodeSelector: {}
    affinity: {}
    podAnnotations: {}
    extraPipPackages: []
    extraVolumeMounts: []
    extraVolumes: []
    resources: {}

  sync:
    resources: {}
    nodeSelector: {}
    affinity: {}
    securityContext:
      fsGroup: 65534
    podLabels: {}
    annotations: {}
    podAnnotations: {}
    safeToEvict: true

###################################
# Airflow - Scheduler Configs
###################################
scheduler:
  replicas: 1
  resources: {}
  nodeSelector: {}
  affinity: {}
  securityContext:
    fsGroup: 65534
  labels: {}
  podLabels: {}
  annotations: {}
  podAnnotations: {}
  safeToEvict: true
  podDisruptionBudget:
    enabled: false
    maxUnavailable: ""
    minAvailable: ""
  numRuns: -1
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 5
  extraPipPackages: []
  extraVolumeMounts: []
  extraVolumes: []
  extraInitContainers: []

###################################
# Airflow - WebUI Configs
###################################
web:
  ## configs to generate webserver_config.py
  ##
  webserverConfig:
    stringOverride: ""
    existingSecret: ""

  replicas: 1
  resources: {}
  nodeSelector: {}
  affinity: {}
  securityContext:
    fsGroup: 65534
  labels: {}
  podLabels: {}
  annotations: {}
  podAnnotations: {}
  safeToEvict: true
  podDisruptionBudget:
    enabled: false
    maxUnavailable: ""
    minAvailable: ""
  service:
    annotations: {}
    sessionAffinity: "None"
    sessionAffinityConfig: {}
    type: NodePort
    externalPort: 8080
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    nodePort:
      http: ""
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  extraPipPackages: []
  extraVolumeMounts: []
  extraVolumes: []

###################################
# Airflow - Celery Worker Configs
###################################
workers:
  enabled: true
  replicas: 2
  resources:
    requests:
      memory: "4Gi"

  podDisruptionBudget:
    enabled: true
    maxUnavailable: "20%"

  autoscaling:
    enabled: true
    maxReplicas: 16
    metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

  ## configs for the celery worker Pods
  ##
  celery:
    instances: 10
    gracefullTermination: true
    gracefullTerminationPeriod: 540
  terminationPeriod: 60
  nodeSelector: {}
  affinity: {}
  tolerations:
    - key: 'spotInstance'
      operator: 'Equal'
      value: 'airflow'
      effect: 'NoSchedule'
  securityContext:
    fsGroup: 65534
  labels: {}
  podLabels: {}
  annotations: {}
  podAnnotations: {}
  safeToEvict: true
  extraPipPackages: []
  extraVolumeMounts: []
  extraVolumes: []
  secretsDir: /var/airflow/secrets
  secrets:
    - clh-password
    - pg-user
    - pg-password


###################################
# Airflow - Flower Configs
###################################
flower:
  enabled: true
  replicas: 1
  resources: {}
  nodeSelector: {}
  affinity: {}
  tolerations: []
  securityContext:
    fsGroup: 65534
  labels: {}
  podLabels: {}
  annotations: {}
  podAnnotations: {}
  safeToEvict: true
  podDisruptionBudget:
    enabled: false
    maxUnavailable: ""
    minAvailable: ""
  oauthDomains: ""
  basicAuthSecret: ""
  basicAuthSecretKey: ""
  service:
    annotations: {}
    type: ClusterIP
    externalPort: 5555
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    nodePort:
      http:

  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

  extraPipPackages: []

  extraVolumeMounts: []
  extraVolumes: []

###################################
# Airflow - Logs Configs
###################################
logs:
  ## the airflow logs folder
  ##
  path: /opt/airflow/efs/logs
  persistence:
    enabled: true
    subPath: ""
    storageClass: "efs-sc"
    accessMode: ReadWriteMany
    size: 1Gi

###################################
# Airflow - DAGs Configs
###################################
dags:
  ## the airflow dags folder
  ##
  path: /opt/airflow/efs/dags
  # gitSync:
  #   enabled: true
  #   repo: "https://gitlab.com/MLOpsEngineer/airflow.git"
  #   branch: "main"
  #   revision: "HEAD"
  #   syncWait: 60
  #   httpSecret: "airflow-http-git-secret"
  #   httpSecretUsernameKey: username
  #   httpSecretPasswordKey: password
    
  # gitSync:
  #   enabled: true
  #   repo: "git@github.com:MLOpsEngineer/airflow-dags.git"
  #   branch: "master"
  #   revision: "HEAD"
  #   syncWait: 60
  #   sshSecret: "airflow-ssh-git-secret"
  #   sshSecretKey: "id_rsa"
    
  #   # "known_hosts" verification can be disabled by setting to "" 
  #   sshKnownHosts: |-
  #     github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
  git:
  ## berrrrr는 제 id입니다. (각자 자기 github id로 변경하세요)
    ## url to clone the git repository (access token은 가립니다). 
    ## airflow-test repository에 DAG를 넣는다고 가정합니다. 
    url: https://mlopsengineer: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@git@github.com:MLOpsEngineer/airflow-dags.git
    ##
    ## branch name, tag or sha1 to reset to
    ref: master
    ## pre-created secret with key, key.pub and known_hosts file for private repos
    secret: 
    ## The host of the repo so for example if a github repo put github.com (Only need if using ssh not https git sync)
    repoHost:
    ## The name of the private key in your git sync secret (Only need if using ssh not https git sync)
    privateKeyName:
    gitSync:
      ## Turns on the side car container
      enabled: true
      ## Image for the side car container
      image:
        ## docker-airflow image (공식 docker이미지입니다. 아래 주소 그대로 써주세요)
        repository: k8s.gcr.io/git-sync
        ## image tag (버전은 이게 최신은아닐거같지만..ㅋ)
        tag: v3.1.1
        ## Image pull policy
        ## values: Always or IfNotPresent
        pullPolicy: IfNotPresent
      ## The amount of time in seconds to git pull dags (sync 맞출 간격입니다. 저는 1분간격으로 땡겨오게했습니다)
      refreshTime: 60 
  initContainer:
    ## Fetch the source code when the pods starts
    enabled: true
    ## Image for the init container (any image with git will do)
    image:
      ## docker-airflow image
      repository: k8s.gcr.io/git-sync 
      ## image tag
      tag: v3.1.1
      ## Image pull policy
      ## values: Always or IfNotPresent
      pullPolicy: IfNotPresent
    ## install requirements.txt dependencies automatically
    installRequirements: true


###################################
# Kubernetes - Service Account
###################################
serviceAccount:
  create: true
  name: "airflow"
  annotations:
    # eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/eks-airflow-sa"
    eks.amazonaws.com/role-arn: "arn:aws:iam::645712393653:user/aicore0094"


extraManifests: []

###################################
# Database - PostgreSQL Chart
# - https://github.com/helm/charts/tree/master/stable/postgresql
###################################
postgresql:
  enabled: true
  postgresqlDatabase: airflow
  postgresqlUsername: postgres
  postgresqlPassword: airflow
  existingSecretKey: "postgresql-password"
  extraEnv:
    - name: BITNAMI_DEBUG
      value: "true"
  persistence:
    enabled: true
    storageClass: "efs-sc"
    existingClaim: "data-airflow-postgresql"
    accessModes:
      - ReadWriteMany
    size: 8Gi

  master:
    podAnnotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  
  volumePermissions:
    enabled: true